name       : kde-cli-tools
version    : 5.12.5
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.5/kde-cli-tools-5.12.5.tar.xz : 905e5ad02a68743674f89bf705ffc32e0772704fee5023e5be068f2e6e6a403f
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
patterns   :
    - /usr/lib64/libkdeinit5*
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
