name       : kde-cli-tools
version    : 5.24.3
release    : 77
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.3/kde-cli-tools-5.24.3.tar.xz : fe64da7ce3ad7e7b2d743e06aec0f6666e1909d3ad08867a0173c5c262f7e803
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kdesu-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - plasma-workspace-devel
patterns   :
    - /usr/lib64/libkdeinit5*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
