name       : kde-cli-tools
version    : 5.10.1
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kde-cli-tools-5.10.1.tar.xz : d46ca37d30fca23759513e77f947d9a85bafcff991755a496dba8b60f183b3a3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
patterns   :
    - /usr/lib64/libkdeinit5*
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
