name       : kde-cli-tools
version    : 5.15.5
release    : 32
source     :
    - https://download.kde.org/stable/plasma/5.15.5/kde-cli-tools-5.15.5.tar.xz : fbff40188d7864a11aa6aea0b6d8cca2c66025924b3cb29275ac6d282ece9ace
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
patterns   :
    - /usr/lib64/libkdeinit5*
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcmutils-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kdesu-devel
    - ki18n-devel
    - kio-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
