name       : kde-cli-tools
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kde-cli-tools-5.9.5.tar.xz : 56e4835deed5d81c37a69efbb399d5f59bb894da33077d251a2374ecf423d0a4
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
patterns   :
    - /usr/lib64/libkdeinit5*
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
