name       : kde-cli-tools
version    : 5.23.5
release    : 75
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/kde-cli-tools-5.23.5.tar.xz : 4d16ae5a5b0f727cee617c89c6d8fc259e12789c44ba4c77c0b036120ffa0388
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kdesu-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - plasma-workspace-devel
patterns   :
    - /usr/lib64/libkdeinit5*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
