name       : kde-cli-tools
version    : 5.26.3
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.3/kde-cli-tools-5.26.3.tar.xz : fbbfcb5e4d9fac5b4e2df1b4d2af4adb0de83630e2fb0369098d30366de2e640
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kdesu-devel
    - kiconthemes-devel
    - kinit-devel
    - kparts-devel
    - plasma-workspace-devel
patterns   :
    - /usr/lib64/libkdeinit5*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
