name       : kde-cli-tools
version    : 5.22.2
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/kde-cli-tools-5.22.2.1.tar.xz : f37da67d3f46ca3bf353bbfeb36e5b7cd0ad3f0e923a530dfac9c1a280cc90c2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 5 to better interact with the system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kdesu-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - plasma-workspace-devel
patterns   :
    - /usr/lib64/libkdeinit5*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
